### ISSUE TITLE
Bible Text API

### ISSUE THREAD

**Issue by rober42539** [lifechurch/youversion-public-api-docs#6]
It would be great to have an API to access content from the Bible (chapter, verse, audio, etc) in the language of choice.

**Comment by bbelyeu** [comment]
We do not own any Bible texts. We (LifeChurch) have not translated or copyrighted any Bible versions. We have legal agreements that allow us to use some publisher's Bible versions in our app. We're working on getting more to allow us to use their versions in the public apis. If you would like to have access to their Bible texts, you may sign up for an account on the Digital Bible Library (https://thedigitalbiblelibrary.org/) like we did or you may give a try to the newer https://scripture.api.bible/ owned by the American Bible Society.
